stages:
  - build
  # - release

build_image:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - echo $CI_BUILD_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_NAME"
    - docker push "$CI_REGISTRY_IMAGE"
  

# release:
#   only:
#     - master
#   stage: release
#   before_script:
#     - curl https://cli-assets.heroku.com/install.sh | sh
#   script:
#     - docker login -u _ -p ${HEROKU_AUTH_TOKEN} registry.heroku.com
#     - docker push ${HEROKU_REGISTRY_IMAGE}
#     - heroku container:release --app kbd-webapp web